name: Auto Pull Request

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add any necessary steps here, such as running tests or building your project
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test
          base: main
          title: Automated Pull Request
          body: |
            This is an automated pull request created by a GitHub Action.
